spring.application.name=demo
server.port=8080
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/leanodb
spring.datasource.username=leanodb
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/leano
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
>>>>>>> d77fc686effe7560f99347f1448f00b3c116ea40
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true